version: '3'
services:
  server:
    # image: xxxx.com/jr-cms-17
    build: .
    # image: node:16
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    environment:
      - JWT_KEY=secret
      - CONNECTION_STRING=mongodb://mongo/jrCms17
    ports:
      - 3000:3000
    container_name: jr-cms-17_server
    depends_on:
      - mongo
    # command: >
    #   sh -c "cd /app && npm i && npm run dev"

  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: jr-cms-17_mongo