name: 'jr cms 17'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy [1,2] [a,b] -> 1a, 1b, 2a, 2b matrix

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: use node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: install dep
        run: npm i

      - name: run tests
        run: npm test
